[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.6.0"
  YARN_FLAGS = "--no-ignore-optional"
[[redirects]]
  from = "/*"
  to = "https://www.220plus.su/:splat"
