[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.6.0"
  YARN_FLAGS = "--no-ignore-optional"
[[redirects]]
  from = "https://vigorous-banach-75b1b6.netlify.com/*"
  to = "https://220plus.su/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 503
  force = true
