backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img
slug:
  encoding: "unicode"
  clean_accents: true

collections:
  - name: "categories"
    label: "Categories"
    folder: "src/pages/categories"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "category-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
  - name: "products"
    label: "Products"
    folder: "src/pages/products"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Categories", name: "categories", widget: "relation", collection: "categories", searchFields: ["title"], valueField: "title"}
