backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: "categories"
    label: "Категории"
    folder: "src/pages/categories"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "category-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
  - name: "product-company"
    label: "Компании продуктов"
    folder: "src/pages/product-company"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-company-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
  - name: "products"
    label: "Продукты"
    folder: "src/pages/products"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Categories", name: "categories", widget: "relation", collection: "categories", searchFields: ["title"], valueField: "title"}
  - name: "special-offers"
    label: "Специальные предложения"
    folder: "src/pages/special-offers"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "special-offer-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}