backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "categories"
    label: "Категории продуктов"
    folder: "src/pages/categories"
    create: true
    fields:
      - {label: "Контент тип", name: "contentType", widget: "hidden", default: "category"}
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Изображение", name: "image", widget: "image"}
      - {label: "Описание", name: "description", widget: "text"}
    editor:
      preview: false
  - name: "product-company"
    label: "Компании продуктов"
    folder: "src/pages/product-company"
    create: true
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Изображение", name: "image", widget: "image"}
      - {label: "Контент тип", name: "contentType", widget: "hidden", default: "productCompany"}
    editor:
      preview: false
  - name: "products"
    label: "Продукты"
    folder: "src/pages/products"
    create: true
    fields:
      - {label: "Идентификатор шаблона", name: "templateKey", widget: "hidden", default: "product-page"}
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Категория", name: "categories", widget: "relation", collection: "categories", searchFields: ["title"], valueField: "title"}
      - {label: "Изображение", name: "image", widget: "image"}
      - {label: "Цена", name: "price", widget: "number"}
      - {label: "Описание", name: "body", widget: "markdown"}
    editor:
     preview: false
  - name: "special-offers"
    label: "Специальные предложения"
    folder: "src/pages/special-offers"
    create: true
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Изображение", name: "image", widget: "image"}
      - {label: "Контент тип", name: "contentType", widget: "hidden", default: "specialOffer"}
    editor:
      preview: false
  - name: "pages"
    label: "Страницы"
    files:
      - file: "src/pages/about/index.md"
        label: "О компании"
        name: "about"
        fields:
          - {label: "Идентификатор", name: "id", widget: "hidden", default: "about-section"}
          - {label: "Контент тип", name: "contentType", widget: "hidden", default: "section"}
          - {label: "Заголовок", name: "title", widget: "string"}
          - {label: "Текст", name: "body", widget: "markdown", buttons: ["bold", "italic", "link", "heading-two", "heading-three", "heading-four", "heading-five", "heading-six", "quote", "quote-block", "bullet-list", "numbered-list"]}
      - file: "src/pages/delivery/index.md"
        label: "Доставка и оплата"
        name: "delivery"
        fields:
          - {label: "Идентификатор шаблона", name: "templateKey", widget: "hidden", default: "delivery-page"}
          - {label: "Идентификатор", name: "id", widget: "hidden", default: "delivery-section"}
          - {label: "Контент тип", name: "contentType", widget: "hidden", default: "section"}
          - {label: "Заголовок", name: "title", widget: "string"}
          - {label: "Текст", name: "body", widget: "markdown", buttons: ["bold", "italic", "link", "heading-two", "heading-three", "heading-four", "heading-five", "heading-six", "quote", "quote-block", "bullet-list", "numbered-list"]}
      - file: "src/pages/warehouse/index.md"
        label: "Склад самовывоза"
        name: "warehouse"
        fields:
          - {label: "Идентификатор шаблона", name: "templateKey", widget: "hidden", default: "warehouse-page"}
          - {label: "Идентификатор", name: "id", widget: "hidden", default: "warehouse-section"}
          - {label: "Контент тип", name: "contentType", widget: "hidden", default: "section"}
          - {label: "Заголовок", name: "title", widget: "string"}
          - {label: "Текст", name: "body", widget: "markdown", buttons: ["bold", "italic", "link", "heading-two", "heading-three", "heading-four", "heading-five", "heading-six", "quote", "quote-block", "bullet-list", "numbered-list"]}
      - file: "src/pages/testimonials/index.md"
        label: "Отзывы"
        name: "testimonials"
        fields:
          - {label: "Идентификатор шаблона", name: "templateKey", widget: "hidden", default: "testimonials-page"}
          - {label: "Идентификатор", name: "id", widget: "hidden", default: "testimonials-section"}
          - {label: "Контент тип", name: "contentType", widget: "hidden", default: "section"}
          - {label: "Заголовок", name: "title", widget: "string"}
          - {label: "Текст", name: "body", widget: "markdown", buttons: ["bold", "italic", "link", "heading-two", "heading-three", "heading-four", "heading-five", "heading-six", "quote", "quote-block", "bullet-list", "numbered-list"]}
      - file: "src/pages/contact/index.md"
        label: "Контакты"
        name: "contact"
        fields:
          - {label: "Идентификатор шаблона", name: "templateKey", widget: "hidden", default: "contact-page"}
          - {label: "Идентификатор", name: "id", widget: "hidden", default: "contact-section"}
          - {label: "Контент тип", name: "contentType", widget: "hidden", default: "section"}
          - {label: "Заголовок", name: "title", widget: "string"}
          - {label: "Текст", name: "body", widget: "markdown", buttons: ["bold", "italic", "link", "heading-two", "heading-three", "heading-four", "heading-five", "heading-six", "quote", "quote-block", "bullet-list", "numbered-list"]}
    editor:
      preview: false
  